# Utilizza l'immagine ufficiale di Ubuntu come immagine di base
FROM ubuntu:22.04

# Aggiorna e installa i pacchetti necessari
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    ninja-build \
    cmake \
    ruby \
    file \
    python3 \
    micro \
    python3-pip \
    net-tools \
    iputils-arping\
    tcpdump \
    dsniff

# Abilita l'IP forwarding
RUN echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

RUN pip install scapy
RUN apt-get update && apt-get install -y libpcap0.8

# Imposta la directory di lavoro su /root
WORKDIR /root

# Copia il file gps_simulator.py nell'immagine

COPY container_Attacker/attack_final.py /root/
COPY container_Attacker/attack_final2.py /root/
COPY container_Attacker/attackMSP.py /root/
COPY container_Attacker/Coordinate_Attacco.txt /root/

CMD ["/bin/bash"]
