all: scenario1 scenario2 scenario3

scenario1:
	./genScript.sh -a architecture.pl -r interaction_rules.P -o ex1

scenario2:
	./genScript.sh -a architecture2.pl -r interaction_rules.P -o ex2

scenario3:
	./genScript.sh -a architecture3.pl -r interaction_rules.P -o ex3