# Utilizza l'immagine ufficiale di Ubuntu come immagine di base
FROM ubuntu:22.04

# Aggiorna e installa i pacchetti necessari
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    ninja-build \
    cmake \
    ruby \
    file \
    python3 \
    python3-pip

# Imposta la directory di lavoro su /root
WORKDIR /root

# Copia il file gps_simulator.py nell'immagine
COPY gps_nmea_SGTD_FG.py /root/
COPY gps_nmea.txt /root/


CMD ["/bin/bash"]